# Generated by Django 2.0 on 2020-08-25 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('mini_url', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('created_by', models.CharField(max_length=40, verbose_name='Créé par')),
                ('nb_access', models.SmallIntegerField(default=0, verbose_name='nombre de redirections')),
            ],
            options={
                'verbose_name': 'Mini Url',
                'verbose_name_plural': 'Minis URL',
            },
        ),
    ]
