# Generated by Django 2.0 on 2020-08-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200823_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
